runtime: nodejs16
service: dev

# instance_class: F4

# automatic_scaling:
#   min_idle_instances: 10
#   max_idle_instances: automatic
#   min_pending_latency: 0.030s
#   max_pending_latency: automatic
#   target_cpu_utilization: 0.6
#   min_instances: 5

# default_expiration: "15m"

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    expiration: 15m
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: "0.0.0.0"
